version: "3.4"
services:  
  nginx:
    image: ghcr.io/solutas/soluneo/solcache:production-development
    container_name: solcache-prod-$rand
    volumes:
      - ./files:/data/files
      - ./config:/home/config
      - ./projects:/data/projects    
    environment: 
      - API_SERVER_URL=solserver-prod:8080
      - WEBAPP_SERVER_URL=yajui-prod:3001
      - DELIVERY_SERVER_URL=soldelivery-prod:1619
    depends_on:
      - server
      - webapp
    ports:
      - "80:80"
      - "443:443"
  webapp:
    image: ghcr.io/solutas/soluneo/solui:production
    container_name: yajui-prod-$rand
    expose:
      - "3001"
    stdin_open: true          
    depends_on:
      - server
  server:
    image: ghcr.io/solutas/soluneo/server:production
    container_name: solserver-prod-$rand
    volumes:
    - ./files:/home/files
    - ./packages:/home/packages
    - ./config:/home/config
    - ./actions:/home/actions
    environment:
    - REDIS_URL=redis://redis
    - MONGO_URL=mongodb://mongo-yaj-$rand
    - GOOGLE_APPLICATION_CREDENTIALS=/home/config/nghelvetia-afc5d9885d0d.json  
    expose:
    - "8080"
    depends_on:
      - mongo
      - redis
  delivery:
    image: ghcr.io/solutas/soluneo/delivery:production
    container_name: soldelivery-prod-$rand
    volumes:
    - ./delivery-server:/home/server
    - ./files:/home/files
    - ./packages:/home/packages
    - ./config:/home/config
    - ./actions:/home/actions
    environment:
    - REDIS_URL=redis://redis-yaj-$rand
    - MONGO_URL=mongodb://mongo-yaj-$rand
    - PORT=1619
    - ES_URL=http://es01:9200    
    - GOOGLE_APPLICATION_CREDENTIALS=/home/config/nghelvetia-afc5d9885d0d.json  
    expose:
    - "1619"
    depends_on:
    - server
  redis:
    image: redis:latest
    container_name: redis-yaj-$rand
    volumes:
       - ./redis-data:/var/lib/redis
    expose:
    - "6379"    
  mongo:
    image: mongo
    container_name: mongo-yaj-$rand
    expose:
    - "27017"    
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null      
    volumes:
      - ./data:/data/db:rw
    restart: always